### ISSUE TITLE
Incompatible with 4.0.0

### ISSUE THREAD

**Issue by LaurensRietveld** [tleish/redmine_remote_revision_url#15]
When trying to migrate this plugin in redmine 4.0.0, I'm getting the following stack trace:

```
Migrating plugins. Please be patient, this could take a while...
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activemodel-5.2.2/lib/active_model/validations/clusivity.rb:8: warning: already initialized constant ActiveModel::Validations::Clusivity::ERROR_MESSAGE
/home/redmine/data/tmp/bundle/ruby/2.3.0/gems/activemodel-5.2.2/lib/active_model/validations/clusivity.rb:8: warning: previous definition of ERROR_MESSAGE was here
rake aborted!
NoMethodError: undefined method `to_prepare' for ActionDispatch::Callbacks:Class
/home/redmine/redmine/plugins/redmine_remote_revision_url/init.rb:4:in `<top (required)>'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
```

ps. thanks for this plugin btw, very useful

**Comment by tleish** [comment]
I no longer use Redmine and cannot effectively update and maintain this repo.  Let me know if interested in taking it over?
